#!/usr/bin/env python

from multiprocessing import Process
from subprocess import call
import time
import os, sys
import subprocess
import redis
import signal

MAIN_PORT = 2000

def create_redis_server(port):
    if not os.path.exists(port):
        os.mkdir(port)
    
    orgin_path = os.getcwd()
    os.chdir(port)
    cmds = ["redis-server", "--port", port]
    ret = call(cmds, stdout=open(os.devnull, "w"), stderr=subprocess.STDOUT) 
    sys.exit(0)

def create_server(port):
    portnumber = str(port)
    p = Process(target=create_redis_server, args=(portnumber,))
    p.start() 
    print("Redis server created, [PID]: %s" % p.pid)
    
    r = redis.Redis(port=portnumber)
    while True:
        try:
            print("Start connecting to port %s ..." % portnumber)
            time.sleep(2)
            r.ping()
        except redis.exceptions.ConnectionError:
            print("Connected to port %s failed, restarting ..." % portnumber)
            pass
        else:
            print("Connected successfully!")
            break  
    return p

def redis_initialize(r):
    portlist = r.keys()
    for port in portlist:
        proc = create_server(port)
        print("pid = %s" % proc.pid)

def initialize():
    print("Booting redis-DB manager ...")
    create_server(MAIN_PORT)    # Create redis-server manager
    
    redis_manager = redis.Redis(port=MAIN_PORT)
    redis_initialize(redis_manager)          # Initialized profiling DB

def main():
    initialize()

def keyboard_int_handler(signal, frame):
    print("[PID %s] Stop profiling server ..." % os.getpid())
    sys.exit(0)

if __name__ == "__main__":
    signal.signal(signal.SIGINT, keyboard_int_handler)
    main()
        
